


spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/lienmall?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        connection:
          driver_class: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/lienmall?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: 1234
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
